CREATE TABLE IF NOT EXISTS users(
    username VARCHAR(32) PRIMARY KEY UNIQUE NOT NULL,
    token TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
)